# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='mpoly',
        ),
        migrations.AddField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(1, 1), srid=4326),
        ),
    ]
