# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_session', '0001_initial'),
        ('user_session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_session.Address')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='residentialAddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='address_session.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathinstance',
            name='appUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_session.AppUser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='path',
            field=models.ManyToManyField(through='user_session.PathInstance', to='address_session.Address'),
        ),
    ]
