# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0003_auto_20171113_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='path',
            field=models.ManyToManyField(through='user_session.PathInstance', to='address_session.Address'),
        ),
    ]
