# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0006_auto_20171113_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathinstance',
            old_name='address_point',
            new_name='address',
        ),
    ]
