# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_session', '0002_auto_20171113_1623'),
        ('address_session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=600)),
                ('date', models.DateTimeField()),
                ('address', models.ManyToManyField(to='address_session.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_session.EventOwner')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='event_session.Tag'),
        ),
    ]
